language: python

python:
  - 2.7
script:
  - python helloworld.py
GET /sureshpuram
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
    local-dir: ./index.html
